### ISSUE TITLE
Incompatibility issue with flax

### ISSUE THREAD

**Issue by miguelamendez** [alvarobartt/safejax#30]
importing  the safejax library I get the following warning from flax
FutureWarning: jax.tree_util.register_keypaths is deprecated, and will be removed in a future release. Please use `register_pytree_with_keys()` instead.

**Comment by alvarobartt** [comment]
Hi @miguelamendez, is it just when importing it? Which version of `safejax` are you using? Can you install `safetensors` separately and let me know whether `import safetensors` fails or not? Thanks

**Comment by miguelamendez** [comment]
Yes just when importing it.
Just realized importing flax by itself also triggers that error so shouldn't be a problem from safejax. I'll try to reinstall flax to see if the issue is solved.
Thanks.
